### ISSUE TITLE
zstd license violation

### ISSUE THREAD

**Issue by isuruf** [conda-forge/zstandard-feedstock#43]
This package uses the C library zstd which is BSD-3-Clause.

Please re-distribute that file found in https://github.com/indygreg/python-zstandard/blob/main/zstd/LICENSE
Or better yet, use the `zstd` conda package with `--with-system-zstd` option at https://github.com/indygreg/python-zstandard/blob/6006fdf164ac0e89b260706a3e4ef5806aceffb6/setup.py#L64

**Comment by dholth** [comment]
This should go into recipe/meta.yaml

```
  license_file:
    - LICENSE
    - zstd/LICENSE
```
